"""empty message

Revision ID: 73afaf158bec
Revises: 43ef4765fb6f
Create Date: 2026-07-05 18:56:27.110479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73afaf158bec'
down_revision: Union[str, Sequence[str], None] = '43ef4765fb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'captain_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'captain_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
